# Generated by Django 3.1.5 on 2021-01-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='vm_id',
        ),
    ]
