# Generated by Django 3.1.5 on 2021-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_storagedisk_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='xml',
        ),
        migrations.AddField(
            model_name='vm',
            name='state',
            field=models.CharField(default='OFF', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vm',
            name='hypervisor',
            field=models.CharField(choices=[('QEMU', 'QEMU'), ('Virtualbox', 'Virtualbox'), ('VMWare', 'VMWare')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vm',
            name='os',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Mac', 'Mac')], max_length=30),
        ),
    ]
