# Generated by Django 3.1.5 on 2021-03-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210325_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkMode', models.CharField(max_length=30)),
                ('VM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VMs', to='manager.vm')),
            ],
        ),
        migrations.AddField(
            model_name='vm',
            name='advanced_options',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='VMs', to='manager.advancedvm'),
            preserve_default=False,
        ),
    ]
