# Generated by Django 3.1.5 on 2021-03-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210326_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='advanced_options',
        ),
        migrations.DeleteModel(
            name='AdvancedVM',
        ),
    ]
