# Generated by Django 3.1.5 on 2021-03-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_mode',
        ),
        migrations.AddField(
            model_name='profile',
            name='advanced_mode',
            field=models.BooleanField(default=False),
        ),
    ]
