# Generated by Django 3.1.5 on 2021-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_opticaldisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticaldisk',
            name='ImageFile',
            field=models.FileField(upload_to='bruh'),
        ),
    ]
