# Generated by Django 3.1.5 on 2021-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20210326_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedisk',
            name='type',
            field=models.CharField(choices=[('qcow2', 'qcow2'), ('vhd', 'vhd')], max_length=30),
        ),
    ]
