# Generated by Django 3.1.5 on 2021-03-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20210326_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='optical_disk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.opticaldisk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vm',
            name='storage_disk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.storagedisk'),
        ),
    ]
