# Generated by Django 3.1.5 on 2021-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20210326_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticaldisk',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
