# Generated by Django 3.1.5 on 2021-03-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_opticaldisk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='optical_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.opticaldisk'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='storage_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.storagedisk'),
        ),
    ]
