# Generated by Django 3.1.5 on 2021-04-06 19:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
