# Generated by Django 3.1.5 on 2021-04-06 20:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_remove_xml_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
    ]
