# Generated by Django 3.1.5 on 2021-04-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_xml_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='content',
            field=models.TextField(),
        ),
    ]
