# Generated by Django 3.1.5 on 2021-04-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20210406_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XML',
            new_name='customVM',
        ),
    ]
