# Generated by Django 3.1.5 on 2021-04-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20210406_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvm',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storagedisk',
            name='type',
            field=models.CharField(choices=[('qcow2', 'qcow2'), ('vmdk', 'vmdk')], max_length=30),
        ),
    ]
