# Generated by Django 3.1.5 on 2021-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20210415_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvm',
            name='hypervisor',
            field=models.CharField(choices=[('QEMU', 'QEMU'), ('Virtualbox', 'Virtualbox'), ('VMWare', 'VMWare')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customvm',
            name='state',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
