# Generated by Django 3.1.5 on 2021-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_auto_20210419_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cpus', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('app', models.CharField(default='/bin/sh', max_length=30)),
            ],
        ),
    ]
