# Generated by Django 3.1.5 on 2021-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedisk',
            name='path',
            field=models.CharField(max_length=30),
        ),
    ]
