# Generated by Django 3.1.5 on 2021-04-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_auto_20210419_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='hypervisor',
            field=models.CharField(default='lxc', max_length=3),
        ),
    ]
