# Generated by Django 3.1.5 on 2021-04-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_container_hypervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='state',
            field=models.CharField(default='OFF', max_length=3),
        ),
    ]
