# Generated by Django 3.2.8 on 2021-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_container_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('DiskFile', models.FileField(upload_to='Disks')),
            ],
        ),
    ]
